import {
  LoginButton,
  LogoutButton,
  ProfileButton,
  RegisterButton,
} from "@/components/buttons";
import "../globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { redirect } from "next/navigation";
import Link from "next/link";
import Providers from "../Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (!session) {
    redirect("/api/auth/signin");
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <section>
          <Link href="/">Home</Link>
          <LogoutButton />
          <Link href="/protected">Protected</Link>
          <ProfileButton />
          <br />
          {session?.user?.email} {session?.expires}
        </section>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
